# Generated by Django 5.2.7 on 2025-11-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_work_request_table',
            old_name='request',
            new_name='work_request',
        ),
    ]
