# Generated by Django 5.2.7 on 2025-11-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_request_user_work_request_table_work_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='myapp.login_table'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hh', to='myapp.login_table'),
        ),
    ]
