# Generated by Django 5.2.7 on 2025-11-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_chat_user_id_alter_chat_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hh', to='myapp.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl', to='myapp.login_table')),
            ],
        ),
        migrations.DeleteModel(
            name='chat',
        ),
    ]
